set(HARTREEFOCK_HEADERS
        Kiwi/HartreeFock/HartreeFockMain.h
        Kiwi/HartreeFock/HartreeFockSettings.h
        Kiwi/HartreeFock/FockMatrixBuilder.h
        Kiwi/HartreeFock/ConvergenceAccelerator.h
        Kiwi/HartreeFock/HartreeFockUtils.h
        Kiwi/HartreeFock/SecondOrder.h
        Kiwi/HartreeFock/BFGSScf.h
        Kiwi/HartreeFock/StabilityAnalysis.h
        Kiwi/HartreeFock/BFGS/Optimizer.h
        Kiwi/HartreeFock/BFGS/Interface.h
        Kiwi/HartreeFock/BFGS/Builder.h
        Kiwi/HartreeFock/SecondOrder/ArhBuilder.h
        Kiwi/HartreeFock/SecondOrder/ArhInterface.h
        Kiwi/HartreeFock/SecondOrder/Driver.h
        Kiwi/HartreeFock/SecondOrder/ArhDavidson.h
        Kiwi/HartreeFock/SecondOrder/SigmaVectorEvaluator.h
        Kiwi/HartreeFock/SecondOrder/ModifiedDavidson.h
        Kiwi/HartreeFock/SecondOrder/ModifiedDavidsonNewtonRhapson.h
        Kiwi/HartreeFock/Scf.h
        Kiwi/HartreeFock/AlternatingScf.h
        Kiwi/HartreeFock/SerialScf.h
        Kiwi/HartreeFock/Projector/Projector.h
        Kiwi/HartreeFock/Projector/ProjectorTraits.h
        Kiwi/HartreeFock/Projector/IdentityProjector.h
        Kiwi/HartreeFock/SymmetryProjection/SymmetryTypes.h
        Kiwi/HartreeFock/InitialGuess/Read.h
        Kiwi/HartreeFock/InitialGuess/SAD.h
        Kiwi/HartreeFock/InitialGuess/InitialGuess.h
        Kiwi/HartreeFock/InitialGuess/SND.h
        Kiwi/HartreeFock/FockMatrix/BoHelper.h
        Kiwi/HartreeFock/FockMatrix/PreBoHelper.h
        Kiwi/HartreeFock/FockMatrix/CoulombExchangeMatrices.h
        Kiwi/HartreeFock/FockMatrix/TwoTypeCoulomb.h
        Kiwi/HartreeFock/SimultaneousDiis/SimultaneousDiis.h
        )

set(HARTREEFOCK_SOURCES
        Kiwi/HartreeFock/HartreeFockMain.cpp
        Kiwi/HartreeFock/FockMatrixBuilder.cpp
        Kiwi/HartreeFock/Projector/Projector.cpp
        Kiwi/HartreeFock/ConvergenceAccelerator.cpp
        Kiwi/HartreeFock/Projector/IdentityProjector.cpp
        Kiwi/HartreeFock/SecondOrder/ArhBuilder.cpp
        Kiwi/HartreeFock/InitialGuess/Read.cpp
        Kiwi/HartreeFock/InitialGuess/InitialGuess.cpp
        Kiwi/HartreeFock/InitialGuess/SAD.cpp
        Kiwi/HartreeFock/InitialGuess/SND.cpp
        Kiwi/HartreeFock/SimultaneousDiis/SimultaneousDiis.cpp
        )
