set(KIWIUTILS_HEADERS
        Kiwi/KiwiUtils/GeneralUtility.h
        Kiwi/KiwiUtils/Data.h
        Kiwi/KiwiUtils/SymmetryEnums.h
        Kiwi/KiwiUtils/ParticleDensity/Engine.h
        Kiwi/KiwiUtils/ParticleDensity/Evaluator.h
        Kiwi/KiwiUtils/AO2MO.h
        Kiwi/KiwiUtils/AO2MOHelper.h
        Kiwi/KiwiUtils/BoFciDumper.h
        Kiwi/KiwiUtils/NaturalOrbitals.h
        Kiwi/KiwiUtils/Loewdin.h
        Kiwi/KiwiUtils/MolecularOrbitalsIO.h
        Kiwi/KiwiUtils/Molecule.h)

set(KIWIUTILS_SOURCES
        Kiwi/KiwiUtils/Data.cpp
        Kiwi/KiwiUtils/ParticleDensity/Evaluator.cpp
        Kiwi/KiwiUtils/BoFciDumper.cpp
        Kiwi/KiwiUtils/NaturalOrbitals.cpp
        Kiwi/KiwiUtils/MolecularOrbitalsIO.cpp
        Kiwi/KiwiUtils/Molecule.cpp)
